services:
  - type: web
    name: email-classifier-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GEMINI_API_KEY
        value: AIzaSyABzT2WHlchncvEAeF0GSsgTTWAIDgiCzw
        sync: false