"""adiciona campo smtp_password ao model User

Revision ID: 76f3f17b2910
Revises: 2d2656d54cac
Create Date: 2025-07-18 20:08:06.654448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76f3f17b2910'
down_revision = '2d2656d54cac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('smtp_password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('smtp_password')

    # ### end Alembic commands ###
