"""Initial schema

Revision ID: 97413862ab2b
Revises: 
Create Date: 2025-07-17 02:01:24.476113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97413862ab2b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_text', sa.Text(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('suggested_response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('email_records')
    # ### end Alembic commands ###
